[package]
name = "rusttcp"
version = "0.1.0"
edition = "2021"

[dependencies]
tun = "0.6.1"
etherparse = "0.15"
log = "0.4.22"
env_logger = "0.11.5"
ctor = "0.2.8"

[features]
mocks = []

[dev-dependencies]
rusttcp = { path = ".", features = ["mocks"] }
